### ISSUE TITLE
how would I make a user?

### ISSUE THREAD

**Issue by matthiasdebernardini** [SoTeKie/htmx-axum-maud#1]
Hey thanks for this example, 

I am looking to make something similar, how are you making new users for this? 

For now I just need a default user to test and develop the application with.

Any help is greatly appreciated thanks again!

**Comment by SoTeKie** [comment]
Hi, I ended up kinda abandoning this template for a few reasons (time, looking at other stacks like gleam and me making a few mistakes with this one).

A brief overview is that it's missing here, you'd need to add the FE parts like the form etc., and for the BE logic you'd mostly just want an insert query for the user with some validation (unique email/username if no constraint in db, password length etc.) and then authenticate the user using the same logic you would for login.

It might be a bit messy with how I laid it out, but should be doable. I won't be extending this template or doing anything with it

**Comment by matthiasdebernardini** [comment]
hey all good! I used it for inspiration, thanks for making it!
